name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
        dc: [dmd-2.094.0]
        os: [ubuntu-20.04]
        ros2-distro: [foxy]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - uses: ros-tooling/setup-ros@v0.1
      - name: Install additional dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-shell catkin_pkg
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            ros-${{ matrix.ros2-distro }}-ament-cmake
      - name: Build
        run: |
          source /opt/ros/${{ matrix.ros2-distro }}/setup.sh
          colcon build --paths ./*
      - name: Test
        run: |
          pytest
